[workspace]
members = [
    "packages/api",
    "packages/compiler-cranelift",
    "packages/compiler-llvm",
    "packages/compiler-singlepass",
    "packages/engines",
]
exclude = [
    "packages/any",
]
